### ISSUE TITLE
Mot de passe oublié

### ISSUE THREAD

**Issue by Ripall** [HE-Arc/DrunkYet#21]

**Comment by greut** [comment]
https://laravel.com/docs/master/passwords#resetting-routing ? rtfm ?

**Comment by Ripall** [comment]
> php artisan make:auth 

génère aussi les formulaires d'inscription et de login, ce qu'on a fait autrement.

**Comment by greut** [comment]
![](https://lh3.googleusercontent.com/proxy/7uL_zfYu5Icqmb6fzpJbO1zJAv6nmZeZbC6c5QB2DKBFFGdVCNJL9Lvs-wHQ2__62gW9CxKAoK2Mx1NWCJ0DzYtEoyixQQQcpRyh3jesHLp8iE7HRLtIt4N2nDyibJK7TEI=w461-h262-p)

😜
