### ISSUE TITLE
Utilisateur invité

### ISSUE THREAD

**Issue by Wolfwalker96** [HE-Arc/DrunkYet#24]

**Comment by Wolfwalker96** [comment]
@Globaxe Décidé par @Ripall

**Comment by Globaxe** [comment]
fait à 50% gestion de la supression avec les queues

**Comment by Globaxe** [comment]
tache sur le serveur : 
crontab -e
\* \* \* \* \* php /home/poweruser/www/app/DrunkYet/artisan schedule:run 1>> /dev/null 2>&1
