### ISSUE TITLE
Anti-datage des consommations

### ISSUE THREAD

**Issue by Wolfwalker96** [HE-Arc/DrunkYet#40]

**Comment by Wolfwalker96** [comment]
Anti-datage compliqué. Car on utilise l'heure UTC en interne et que la conversion de l'heure pour le navigateur nécessite de connaitre la timezone du clients.

**Comment by greut** [comment]
http://timeago.org/

**Comment by Wolfwalker96** [comment]
On a préféré un système avec une liste de choix... Cela nous semblait plus ergonomique pour l'utilisateur.

**Comment by greut** [comment]
> Car on utilise leur UTC en interne et que la conversion de l'heure pour le navigateur nécessite de connaitre la timezone du clients.

Où conversion pour le navigateur, correspond à UTC -> humain.

**Comment by greut** [comment]
la timezone du client est connue.

```js
>> (new Date().getHours() - new Date().getUTCHours())
1
```
