### ISSUE TITLE
Présentation

### ISSUE THREAD

**Issue by Wolfwalker96** [HE-Arc/DrunkYet#42]
[DrunkYet.pdf](https://github.com/HE-Arc/DrunkYet/files/1566092/DrunkYet.pdf)

**Comment by greut** [comment]
- poids
- meilleure ergonomie

> _Plus de rafraîchissement pour l’utilisateur et moins pour le serveur_

😕 ??

> _vive le sexisme_

Plus vous choisissez un poids élevé par défaut et un sexe qui par nature tolère mieux l'alcool, moins les gens vont devoir configurer l'application. Le but étant de ne pas être ivre. Je mettrai en mode jeune fille anorexique par défaut :-D

Et les `<meta>` pour en faire une application installable ?

**Comment by Wolfwalker96** [comment]
[DrunkYet.pdf](https://github.com/HE-Arc/DrunkYet/files/1566112/DrunkYet.pdf)

**Comment by Wolfwalker96** [comment]
[DrunkYet.pdf](https://github.com/HE-Arc/DrunkYet/files/1574755/DrunkYet.pdf)
