### ISSUE TITLE
Ressources communes

### ISSUE THREAD

**Issue by Ripall** [HE-Arc/DrunkYet#7]

**Comment by Wolfwalker96** [comment]
vodka.css ajouté et amélioré dans les commits suivant :
* 20310f20dcd1303fbdc910013ff378b74f29409c 
* 2a345e09630952f941411ef25152d98e7298ce8e
* ae72f772fd540383eb1f7d7a325fe77b1ba12aa9

layout.blade.php ajouté dans le commit : 
* 20310f20dcd1303fbdc910013ff378b74f29409c
